project:
  type: book
  output-dir: docs

book:
  title: "Malaria 2000-2017"
  author: ["Feride Karatas", "Amy Yang", "Zora Shi", "Aisling Li"]
  date: today
  date-format: full
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  cookie-consent: true

  sidebar:
    title: "sidebar title"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true

  chapters:
    - index.qmd

    - part: "Effective Teamwork"
      chapters: 
        - src/et/feride-k.qmd
        - src/et/amy-y.qmd
        - src/et/aisling-l.qmd
        - src/et/zora-s.qmd

    - part: "EDA"
      chapters: 
        - src/eda/feride-k.qmd
        - src/eda/amy-y.qmd
        - src/eda/aisling-l.qmd
        - src/eda/zora-s.qmd

  appendices:
    - src/appx/proposal.qmd
    - src/appx/case-study.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    search: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full

execute:
  cache: true

editor: 
  mode: source
  markdown:
    wrap: sentence

