---
title: "Proposal"
---

Your proposal will go here.

### Number of Malaria Cases from 2010

-   Amy Yang, Riley Karatas, Aisling Li, Zora Shi
-   Malaria is a life-threatening disease caused by parasites that are transmitted to people through the bites of infected female Anopheles mosquitoes. Due to the significance of the cause we will be analyzing malaria cases from 2010 to 2017 in terms of global distribution, as well as changes in case numbers and death rate.
-   1 graph+description/person below we will assign to each person
-   1 graph/class

|         |        |       |                                        |       |       |       |
|---------|--------|-------|----------------------------------------|-------|-------|-------|
| Person  | Day 1  | Day 2 | Day 3                                  | Day 4 | Day 5 | Day 6 |
| Riley   |        |       | scatterplot: Total death cases vs time |       |       |       |
| Amy     |        |       |                                        |       |       |       |
| Zora    |        |       |                                        |       |       |       |
| Aisling |        |       |                                        |       |       |       |

**Graphs:**

Total cases vs time -\> Total cases vs time vs countries --\> Choropleth map accordingly Total death cases vs time Total death cases vs time vs countries Choropleth map accordingly Total cases vs death vs time (the conclusion would be global, not regional) Total cases vs death vs region (regional excluding time variable)
